# Generated by Django 4.1.5 on 2023-01-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_alter_aluno_cpf_alter_aluno_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='celular',
            field=models.CharField(max_length=15),
        ),
    ]
