# Generated by Django 4.1.5 on 2023-01-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_alter_aluno_celular_alter_aluno_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='rg',
            field=models.CharField(default='', max_length=14),
        ),
    ]
